### ISSUE TITLE
Failed to activate the seti-syntax package

### ISSUE THREAD

**Issue by m0nq** [jesseweed/seti-syntax#122]
[Enter steps to reproduce below:]

1. Attempt at updating package within atom, subsequently closing and opening the program produced this stack trace. :]

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [seti-syntax](https://github.com/jesseweed/seti-syntax) package, v1.0.0

### Stack Trace

Failed to activate the seti-syntax package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/Users/Vishnu/.atom/packages/seti-syntax/lib/utility.coffee:1:56)
    at Object.<anonymous> (/Users/Vishnu/.atom/packages/seti-syntax/lib/utility.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Vishnu/.atom/packages/seti-syntax/lib/settings.coffee:2:11)
    at Object.<anonymous> (/Users/Vishnu/.atom/packages/seti-syntax/lib/settings.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/Vishnu/.atom/packages/seti-syntax/lib/main.coffee:3:5)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:332:52
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:322:31
    at ThemeManager.module.exports.ThemeManager.activateThemes (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:320:14)
    at ThemeManager.module.exports.ThemeManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:108:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "highlight-selected",
      "vim-mode",
      "jshint"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
angularjs, v0.3.4
angularjs-styleguide-snippets, v0.7.3
atom-html-preview, v0.1.19
atom-jade, v0.3.0
atom-material-ui, v1.2.10
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
color-picker, v2.1.1
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.8
language-babel, v2.18.6
language-ejs, v0.2.0
language-javascript-jsx, v0.3.7
linter, v1.11.4
merge-conflicts, v1.4.2
minimap, v4.23.2
react, v0.15.0
seti-syntax, v1.0.0
terminal-plus, v0.14.5
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by karlos1337** [comment]
Same here:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: [seti-syntax](https://github.com/jesseweed/seti-syntax) package, v1.0.0


### Stack Trace

Failed to activate the seti-syntax package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/home/carlos/.atom/packages/seti-syntax/lib/utility.coffee:1:56)
    at Object.<anonymous> (/home/carlos/.atom/packages/seti-syntax/lib/utility.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/carlos/.atom/packages/seti-syntax/lib/settings.coffee:2:11)
    at Object.<anonymous> (/home/carlos/.atom/packages/seti-syntax/lib/settings.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/home/carlos/.atom/packages/seti-syntax/lib/main.coffee:3:5)
    at ThemePackage.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/usr/share/atom/resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/theme-manager.js:332:52
    at /usr/share/atom/resources/app.asar/src/config.js:614:16
    at /usr/share/atom/resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:527:28)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:534:24
```

### Commands

```
  2x -2:22.5.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ]
  },
  "seti-syntax": {
    "dynamicColor": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
atom-typescript, v8.9.1
atom-wallaby, v1.0.7
color-picker, v2.1.1
custom-invisibles, v0.1.2
emmet, v2.4.3
file-icons, v1.7.8
fonts, v1.2.0
javascript-snippets, v1.2.1
jshint, v1.8.5
language-jade, v0.7.1
linter, v1.11.4
linter-tslint, v0.9.2
minimap-pigments, v0.2.0
pigments, v0.26.0
semantic-ui, v1.0.7
seti-syntax, v1.0.0

# Dev
No dev packages
```

**Comment by ECMachado** [comment]
And here:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Linux Mint
**Thrown From**: [seti-syntax](https://github.com/jesseweed/seti-syntax) package, v1.0.0


### Stack Trace

Failed to activate the seti-syntax package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/home/emachado/.atom/packages/seti-syntax/lib/utility.coffee:1:56)
    at Object.<anonymous> (/home/emachado/.atom/packages/seti-syntax/lib/utility.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/emachado/.atom/packages/seti-syntax/lib/settings.coffee:2:11)
    at Object.<anonymous> (/home/emachado/.atom/packages/seti-syntax/lib/settings.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/home/emachado/.atom/packages/seti-syntax/lib/main.coffee:3:5)
    at ThemePackage.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/usr/share/atom/resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
```

### Commands

```
     -0:34.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.7.3
color-picker, v2.1.1
emmet, v2.4.3
laravel, v0.7.0
livestyle-atom, v0.1.3
minimap, v4.23.2
seti-syntax, v1.0.0
seti-ui, v1.0.3

# Dev
No dev packages
```

**Comment by jontron** [comment]
Got it as well:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [seti-syntax](https://github.com/jesseweed/seti-syntax) package, v1.0.0


### Stack Trace

Failed to activate the seti-syntax package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/Users/Jonbo/.atom/packages/seti-syntax/lib/utility.coffee:1:56)
    at Object.<anonymous> (/Users/Jonbo/.atom/packages/seti-syntax/lib/utility.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Jonbo/.atom/packages/seti-syntax/lib/settings.coffee:2:11)
    at Object.<anonymous> (/Users/Jonbo/.atom/packages/seti-syntax/lib/settings.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/Jonbo/.atom/packages/seti-syntax/lib/main.coffee:3:5)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:13 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
emmet, v2.4.3
jshint, v1.8.5
language-jade, v0.7.1
language-javascript-jsx, v0.3.7
language-mjml, v1.3.0
linter, v1.11.4
linter-jsxhint, v0.1.2
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-pigments, v0.2.0
pigments, v0.26.0
seti-syntax, v1.0.0

# Dev
No dev packages
```

**Comment by rubencaro** [comment]
The same, on Fedora23 this time.

**Comment by Vrakfall** [comment]
Same on mint 17.3.

**Comment by mneumark** [comment]
Same on Mac OS X 10.11 El Capitan. I think its caused by not having both the Syntax and the UI Theme installed. You need to check the result of `atom.packages.getLoadedPackage('seti-ui')` before calling .path on it.

**Comment by prometheas** [comment]
I had both installed, and still got the error message during packages update. Presumably, `seti-syntax` updated and loaded before `seti-ui`. Definitely do what @mneumark recommends 👍

**Comment by jesseweed** [comment]
Sorry guys, that file actually wasn't even supposed to be in there, was a copy paste goof. Should be fixed now!

**Comment by Vrakfall** [comment]
Yup, seems alrighty now. ;D

**Comment by kevinastone** [comment]
is it not compatible with Atom 1.7?

```
kstone@kstone-mbp ~/.a/packages> apm install seti-ui
Installing seti-ui to $HOME/.atom/packages ✗
No available version compatible with the installed Atom version: 1.7.0
```

**Comment by petemill** [comment]
Still getting this error I'm afraid when using the older version of seti-ui
